name: CD

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      environment:
        type: string
        description: environment to deploy to
        required: true

jobs:
  build:
    name: Deploy AWS CDK Typescript Stack
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.1.0

      - name: Install Node
        uses: actions/setup-node@v3.5.0

      - name: Install Dependencies
        run: npm ci

      - name: Build CDK Stack
        run: npm run build
      
      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: cdkprofile
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Bootstrap
        run: "npx cdk bootstrap --profile cdkprofile"

      - name: Deploy AWS CDK Stack
        run: "npx cdk deploy MyFirstCdkStack --ci --require-approval never --no-asset-metadata"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}