name: CI-CD

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - main

jobs:
  dev-ci:
    uses: ./.github/workflows/ci.yaml
    with:
      environment: dev
    name: Build, Test AWS and Databricks stack for dev
    if: ${{ github.event_name != 'push' }}
    secrets: inherit

  dev-cd:
    uses: ./.github/workflows/cd.yaml
    with:
      environment: dev
    name: Deploy AWS and Databricks stack for dev
    if: ${{ github.event_name == 'push' }}
    secrets: inherit

  qa-ci:
    uses: ./.github/workflows/ci.yaml
    needs: dev-cd
    with:
      environment: qa
    name: Build, Test AWS and Databricks stack for qa
    secrets: inherit

  qa-cd:
    uses: ./.github/workflows/cd.yaml
    needs: qa-ci
    with:
      environment: qa
    name: Deploy AWS and Databricks stack for qa
    secrets: inherit


    

