name: CI

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      environment:
        type: string
        description: environment to deploy to
        required: true

jobs:
  build:
    name: Build and Test AWS CDK Typescript Stack
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Test
        run: echo ${{ inputs.environment }} 
      
      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.1.0

      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
          terraform -v

      - name: Install nvm
        run: |
          cat ~/.bashrc
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          source ~/.bashrc
          command -v nvm
          nvm install 16
          node -v
          npm -v
      
      - name: Install cdktf cli
        run: |
          npm install -g cdktf-cli
          cdktf --version

      - name: Install typescript
        run: |
          npm install -g typescript
          tsc -v

      - name: Install databricks cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      - name: Create databricks profile
        run: |
          echo "[DEFAULT]\n host  = https://dbc-d51bcf67-babb.cloud.databricks.com/?o=5947007577556291\n token = dapib589f39ec00563f64175730eff78cc90" > ~/.databrickscfg

      - name: cdk-databricks
        run: |
          npm install @cdktf/provider-databricks --force
          npm install --save-dev @types/node

      - name: deploy resources
        working-directory: ./cdk-tf   
        run: |
          cdktf synth 
          cdktf diff